### ISSUE TITLE
predict() function

### ISSUE THREAD

**Issue by 1151k** [nmtoan91/lshkrepresentatives#2]
Hi,

Thank you for this clustering method, it is very useful. However, one thing that I think would provide a lot of benefit, is if there was a function, similar to the predict() function in the scikit-learn library, with which one may assign cluster labels to new/old data on a previously trained LSH-k-representatives instance.

Best regards,
Daniil

**Comment by nmtoan91** [comment]
Thank you very much for your recommendation, I will make an update soon

**Comment by nmtoan91** [comment]
@1151k 
I have updated the package, 
Please have a look at the repo
https://pypi.org/project/lshkrepresentatives/

**Comment by 1151k** [comment]
Thanks a lot for this quick turn-around, I appreciate it greatly!

**Comment by 1151k** [comment]
Thanks a lot for this quick turn-around, I appreciate it greatly! 
I assume that if x consists of multiple observations, one should run the predict() function in a loop?

**Comment by nmtoan91** [comment]
@1151k I just updated a new version supporting both single and multiple observations.
By the way, if you are writing a paper, we would greatly appreciate it if you could give a citation to our paper.

Thank you

**Comment by 1151k** [comment]
That's awesome! Thanks a lot! Indeed a paper is in the working making use of this algorithm. I've found LSH-k-reps to be superior to previously tested similar methods, at least for our data. 100% it'll be a citation to this paper. Thanks again!

**Comment by nmtoan91** [comment]
Thanks, Please check the new version again :D. 
Now the model can support strings or non-normalized categorical values.

**Comment by 1151k** [comment]
Great to see! I really hope this algorithm will get the attention it deserves in the future. Keep up the amazing work!
