### ISSUE TITLE
Handling of ordinal and nominal data, respectively

### ISSUE THREAD

**Issue by 1151k** [nmtoan91/lshkrepresentatives#3]
Hi,

Again, thanks for the great algorithm!

I just have a question about instances where there's a mix of ordinal and binary data. Does the algorithm handle all data as nominal, or is it possible for it to handle ordinal and binary/nominal data differently? The thing is that it appears to me, when running with mixed ordinal and binary data, that the algorithm weighs binary variables more (or at least distinguishes them more clearly between clusters), whereas ordinal variables (even though knowing the particular data I've been running the algorithm on there should naturally be groups which are strongly towards either end of the "spectrum") have relatively similar value proportions.

Best regards,
Daniil

**Comment by nmtoan91** [comment]
Hi, It would take me serveral days, please wait

**Comment by nmtoan91** [comment]
@1151k I have updated the algorithm for clustering data of both categorical and numerical values (ordinal and nominal data).
Have a look at: https://github.com/nmtoan91/lshkrepresentatives/blob/main/test_LSHkPrototypes.py

**Comment by 1151k** [comment]
I'm beyond thankful, Toan! 
I'll try it out in the coming days, looks very promising!

**Comment by 1151k** [comment]
Dear @nmtoan91 , 

Many thanks again!

I'm testing out LSHkPrototypes now. I'm just wondering, does the algorithm now make a distinction between nominal and ordinal variables explicitly? Or only between nominal and continuous variables? I just wonder as I see only two arguments regarding that in the function call (attributeMasks,numerical_weight=2, categorical_weight=1), and I'm afraid in my case at least (6 ordinal variables with 3-4 levels) it would be erroneous to define as numerical (even though ordinal data with many levels can be used as numerical data, if I understand correctly).. Would adding a distance measure more explicitly aimed at ordinal data provide benefit here?

Best regards,
Daniil

**Comment by 1151k** [comment]
P.S. I get seemingly sensible results when defining the ordinal variables as numerical in attributeMasks. However, a peculiar error occurs above certain number of clusters (when setting `n_clusters=6` or higher)...

```
Traceback (most recent call last):
  File "/Users/xlisda/Downloads/it/server/research/phd/rs_cm/cluster.py", line 96, in <module>
    cluster_labels = kprototypes.fit(X,attributeMasks,numerical_weight=2, categorical_weight=1)
  File "/Users/xlisda/opt/anaconda3/lib/python3.9/site-packages/LSHkRepresentatives/ClusteringAlgorithm.py", line 94, in fit
    self.DoCluster()
  File "/Users/xlisda/opt/anaconda3/lib/python3.9/site-packages/LSHkRepresentatives/LSHkPrototypes.py", line 287, in DoCluster
    cost , move, count_empty = self.UpdateLabels(representatives, self.X_CATE,representatives_sum, representatives_count,membship,labels_matrix,means_count,means_sum,means)
  File "/Users/xlisda/opt/anaconda3/lib/python3.9/site-packages/LSHkRepresentatives/LSHkPrototypes.py", line 155, in UpdateLabels
    self.MovePoint(ipoint, old_clust,representative_id, representatives_count, representatives_sum,membship,curpoint,labels_matrix,means_count,means_sum  )
  File "/Users/xlisda/opt/anaconda3/lib/python3.9/site-packages/LSHkRepresentatives/LSHkPrototypes.py", line 82, in MovePoint
    means_sum[to_id][ki] += self.X_NUM[point_id][ki]
IndexError: index 6 is out of bounds for axis 0 with size 6
```

It appears as if the error stems from `means_sum[to_id][ki] += self.X_NUM[point_id][ki]`, if I'm not mistaken, but what actually the problem is I do not fully understand. I use a quite large dataset (N=63,060), and the number of variables are 13 (6 ordinal, 7 binary; `attributeMasks = [1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1]`). I have never had this type of issue when running the regular LSHkRepresentatives (with that algorithtm I run up to `n_clusters=10` with no problem)...

Can something in this have to do with the number of numerical (in my case, ordinal in fact..) variables? Because the error seems to occur at n+1 of the number of numerical variables.

Update, when setting a condition to only update `means_sum[to_id][ki]` and `means_sum[from_id][ki]` while `ki < self.d_NUM,` it appears to produce the same results as previously, but not get stuck as previously.. Please let me know if this is in any way an erroneous solution...

```
if  len(means_sum.shape)>1:
    for ki in range(self.k):
        if ki < self.d_NUM:
            means_sum[to_id][ki] += self.X_NUM[point_id][ki]
            means_sum[from_id][ki] -= self.X_NUM[point_id][ki]
```

**Comment by nmtoan91** [comment]
@1151k can you send me a part of your data that can reproduce the same error. It would be helpful if I test with your data

**Comment by 1151k** [comment]
@nmtoan91 , I can't share actual data because of contracts and regulations here, but here's a pseudo-dataset which produces the same error. Note here that there are 3 numerical elements (actually, ordinals; again, not sure if this is an appropriate use or not) and 4 binary elements. The error comes when setting n_clusters to >number of numerical elements, it seems... I read in this paper (https://doi.org/10.3389/feduc.2020.589965) that actually ordinals can be treated as interval in most cases, but I'm still very hesitant about setting 3-4 level-ordinals as numericals.. Would you say it's appropriate, from a statistical point of view? The distribution of levels in these ordinals is not normal, but rather skewed.. (measures of disease severity). And if going with "vanilla" lshkrepresentatives, it appears to me as that would be suboptimal, given that (as far as I understand it at least) variables are all treated as nominals (?), while I would like the levels to be distinguished explicitly in the ordinal variables... Btw I use lshkrepresentatives 1.2.2.

```
import numpy as np
from LSHkRepresentatives.LSHkRepresentatives import LSHkRepresentatives
from LSHkRepresentatives.LSHkPrototypes import LSHkPrototypes

X = np.array([
    [0, 0, 0, 0, 0, 0, 1],
    [2, 1, 3, 0, 1, 0, 0],
    [3, 2, 3, 0, 0, 0, 0],
    [3, 3, 3, 0, 0, 1, 1],
    [0, 3, 3, 1, 1, 0, 1],
    [1, 1, 2, 1, 1, 1, 0],
    [1, 1, 2, 1, 1, 1, 0],
    [1, 1, 2, 1, 1, 1, 0],
    [1, 1, 2, 1, 1, 1, 0],
    [0, 1, 0, 0, 0, 0, 0]
])

attributeMasks = [1, 1, 1, 0, 0, 0, 0]
n_clusters = 4

kprototypes = LSHkPrototypes(n_clusters=n_clusters, n_init=1)
cluster_labels = kprototypes.fit(X, attributeMasks, numerical_weight=1, categorical_weight=1)
```

**Comment by nmtoan91** [comment]
@1151k Sorry, there was a bug in the code of the prototype. Please upgrade your package and try again. 
Cheers,

**Comment by 1151k** [comment]
@nmtoan91 wonderful; many thanks, man! Just tested and it works beautifully! 

Just a last question please if you don't mind. Does the prototypes function work appropriately on ordinals with low number of levels? Or is it better to opt for the representatives function for that (although I'm not sure if that one distinguishes between ordinals and nominals either..)?

Many thanks again and sorry for disturbing you with lots of issues! 

Best regards,
Daniil

**Comment by nmtoan91** [comment]
@1151k Sorry, I'm so clear your question.
However, you may use the weights of CATEGORICAL and NUMERIC to just the importance of the two groups.
For example, this one makes the categoricals 10 times more important than the numericals.
```
cluster_labels = kprototypes.fit(X, attributeMasks, numerical_weight=1, categorical_weight=10)
```
I suggest you turn this weight parameter on your research, maybe it can be a hidden information on your dataset.

**Comment by 1151k** [comment]
@nmtoan91 , no worries! Really appreciate the response! :)
I understand the weighting parameter possibility. I'm just unsure regarding the applicability of the distance matrix calculation on ordinal variables with few levels, is it appropriate for such data? I tried to analyze the corresponding code in kprototypes but could no fully comprehend this, or if it's only appropriate to use in case of nominal + interval data...

**Comment by nmtoan91** [comment]
In the prototype, the categorical data will have their dissimilarity matrix, but the numerical data use Euclid distance as normal.
Is that clear for you?

**Comment by 1151k** [comment]
@nmtoan91, many thanks for the clarification! But in the dissimilarity matrix, are ordinals (with this i mean e.g., Likert-scale-like data, like scales of 0-3 for example) and nominals differentiated (i.e., the levels of difference is accounted for in ordinal variables)? Would it be sensible to swap `np.linalg.norm(center-point)` in my code with something more appropriate for ordinal data?

Update, changing to Manhattan distance (`np.sum(np.abs(center-point))`) gives very good results for my data..

**Comment by nmtoan91** [comment]
@1151k Thanks, It's very nice to hear that.

**Comment by 1151k** [comment]
@nmtoan91 I'll hopefully soon be done with the paper and circulate it with the co-authors. Thank you very much indeed Sir for all assistance and kind help, and the interesting discussions regarding this great algorithm. I'll be sure to add you in Acknowledgements and of course cite the corresponding paper! Again – thank you!
